contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #meerpipe channel"
    url: https://nfcore.slack.com/channels/meerpipe
    about: Discussion about the nf-core/meerpipe pipeline
